config/routes.rb
JukeBox::Application.routes.draw do
  resources :tracks do
    collection do
      post 'search'
      post 'save'
    end
  end

  resources :libraries

  resources :genres

  resources :albums

  resources :artists

  resources :users

end

app/models/track.rb
require 'pry'
require 'soundcloud'
class Track < ActiveRecord::Base
  attr_accessible :album_id, :artist_id, :duration, :genre_id, :img_url, :location, :name, :rating, :track_number
  belongs_to :artists
  belongs_to :albums  

  # def save
  # 	Track.save
  # end

  def self.search(title)
  	# binding.pry
  	client = Soundcloud.new(:client_id => 'd95790c46856021f7718e7ec26913e55')
  	@tracks = client.get('/tracks', :name => "#{title}")
  	# binding.pry
  	track_url = 'http://soundcloud.com/forss/flickermood'
	embed_info = client.get('/oembed', :url => track_url)
	# Track.list << @tracks
	return @tracks
	# binding.pry
   #  @track = Track.find(params[:id]) 
    # @sound_cloud_widget = client.get('/oembed', :url => @tracks.track_url)['html']
  end

  

		# json = HTTParty.get(url)
		# 		results = []
		# 		json.each do |track_info|
		# 			results << Track.new(track_info)
		# 		end
		# 	return results
		# 	end
		# end

end

app/controllers/tracks_controller.rb
require 'pry'
require 'soundcloud'
class TracksController < ApplicationController
  

  def index
    @tracks = Track.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tracks }
    end
  end


  def search 
    # binding.pry
    @tracks = Track.search(params[:search])
    # # binding.pry
    # # search.html
    #   x = 0
    #   i = 0
    #   # @results = {}
    #   while x < @track.length do
    #     # binding.pry
    #     @results = @track[i]
    #     # binding.pry
    #     i += 1
    #     x += 1
    #     @results
    #   end
    # binding.pry
    @tracks
  end
  

  def show
    @track = Track.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @track }
    end
  end

  # GET /tracks/new
  # GET /tracks/new.json
  def new
    @track = Track.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @track }
    end
  end

  # GET /tracks/1/edit
  def edit
    @track = Track.find(params[:id])
  end

  def save
    binding.pry
      @track = Track.new(params[:track])

      respond_to do |format|
        if @track.save
          format.html { redirect_to @track, notice: 'Track was successfully created.' }
          format.json { render json: @track, status: :created, location: @track }
        else
          format.html { render action: "new" }
          format.json { render json: @track.errors, status: :unprocessable_entity }
        end
      end
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(params[:track])

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render json: @track, status: :created, location: @track }
      else
        format.html { render action: "new" }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tracks/1
  # PUT /tracks/1.json
  def update
    @track = Track.find(params[:id])

    respond_to do |format|
      if @track.update_attributes(params[:track])
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    @track = Track.find(params[:id])
    @track.destroy

    respond_to do |format|
      format.html { redirect_to tracks_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/tracks/_form.html.erb
<%= form_for(@track) do |f| %>
  <% if @track.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@track.errors.count, "error") %> prohibited this track from being saved:</h2>

      <ul>
      <% @track.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :track_number %><br />
    <%= f.number_field :track_number %>
  </div>
  <div class="field">
    <%= f.label :rating %><br />
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :img_url %><br />
    <%= f.text_area :img_url %>
  </div>
  <div class="field">
    <%= f.label :duration %><br />
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_area :location %>
  </div>
  <div class="field">
    <%= f.label :album_id %><br />
    <%= f.number_field :album_id %>
  </div>
  <div class="field">
    <%= f.label :genre_id %><br />
    <%= f.number_field :genre_id %>
  </div>
  <div class="field">
    <%= f.label :artist_id %><br />
    <%= f.number_field :artist_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tracks/edit.html.erb
<h1>Editing track</h1>

<%= render 'form' %>

<%= link_to 'Show', @track %> |
<%= link_to 'Back', tracks_path %>

app/views/tracks/index.html.erb
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
<script src="/jquery.masonry.min.js"></script>

<h1>Listing tracks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Track number</th>
    <th>Rating</th>
    <th>Img url</th>
    <th>Duration</th>
    <th>Location</th>
    <th>Album</th>
    <th>Genre</th>
    <th>Artist</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tracks.each do |track| %>
  <tr>
    <td><%= track.name %></td>
    <td><%= track.track_number %></td>
    <td><%= track.rating %></td>
    <td><%= track.img_url %></td>
    <td><%= track.duration %></td>
    <td><%= track.location %></td>
    <td><%= track.album_id %></td>
    <td><%= track.genre_id %></td>
    <td><%= track.artist_id %></td>
    <td><%= link_to 'Show', track %></td>
    <td><%= link_to 'Edit', edit_track_path(track) %></td>
    <td><%= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
                
    <div class="field">
              
              <%= form_tag search_tracks_path, :method => 'post' do %>

              <%= select(:track, :scope, [['Local', 1], ['Soundcloud', 2]]) %>
              

              <%= label_tag(:search, "Search for:") %>
              <%= text_field_tag :search %>
              <%= submit_tag "Search", :name => nil %>
        <% end %>
    </div>

<%= link_to 'New Track', new_track_path %>


    <div class="container cols">
        <img class="item" width="300" height="220" src="images/1000.jpg" alt="Yahoo! Hack 2012 India">
        <div class="item one"></div>
        <div class="item two"></div>
        <img class="item" width="300" height="202" src="images/1700.jpg" alt="Reid Burke Node.js Presentation">
        <div class="item one"></div>
        <img class="item" width="300" height="300" src="images/1020.jpg" alt="Good Read on a Lazy Afternoon"> 
        <div class="item three"></div>
        <img width="300" height="225" src="images/1023.jpg" alt="Pictrendz Winners" class="item">
        <div class="item two"></div>
        <img class="item" width="300" height="300" height="202" src="images/0900.jpg" alt="Afternoon Workspace">
        <div class="item five"></div>
        <div class="item one"></div>
        <img width="300" height="225" src="images/1010.jpg" alt="Durga Puja" class="item">
        <div class="item two"></div>
        <img width="300" height="225" src="images/1230.jpg" alt="Frog" class="item">
        <div class="item six"></div>
        <img class="item" width="300" height="202" src="images/1900.jpg" alt="Winning Moments">
        <div class="item three"></div>
        <img width="300" height="225" src="images/1400.jpg" alt="Diyas" class="item">
        <div class="item two"></div>

        <img class="item" width="300" height="220" src="images/1090.jpg" alt="Yahoo! Hack 2012 India">
        <div class="item one"></div>
        <div class="item two"></div>
        <img class="item" width="300" height="202" src="images/1740.jpg" alt="Reid Burke Node.js Presentation">
        <div class="item one"></div>
        <img class="item" width="300" height="300" src="images/1220.jpg" alt="Good Read on a Lazy Afternoon"> 
        <div class="item three"></div>
        <img width="300" height="225" src="images/0023.jpg" alt="Pictrendz Winners" class="item">
        <div class="item two"></div>
        <img class="item" width="300" height="300" height="202" src="images/0900.jpg" alt="Afternoon Workspace">
        <div class="item five"></div>
        <div class="item one"></div>
        <img width="300" height="225" src="images/1510.jpg" alt="Durga Puja" class="item">
        <div class="item two"></div>
        <img width="300" height="225" src="images/1130.jpg" alt="Frog" class="item">
        <div class="item six"></div>
        <img class="item" width="300" height="202" src="images/0020.jpg" alt="Winning Moments">
        <div class="item three"></div>
        <img width="300" height="225" src="images/1490.jpg" alt="Diyas" class="item">
        <div class="item two"></div>

        <img class="item" width="300" height="220" src="images/1090.jpg" alt="Yahoo! Hack 2012 India">
        <div class="item one"></div>
        <div class="item two"></div>
        <img class="item" width="300" height="202" src="images/1740.jpg" alt="Reid Burke Node.js Presentation">
        <div class="item one"></div>
        <img class="item" width="300" height="300" src="images/1220.jpg" alt="Good Read on a Lazy Afternoon"> 
        <div class="item three"></div>
        <img width="300" height="225" src="images/0023.jpg" alt="Pictrendz Winners" class="item">
        <div class="item two"></div>
        <img class="item" width="300" height="300" height="202" src="images/0900.jpg" alt="Afternoon Workspace">
        <div class="item five"></div>
        <div class="item one"></div>
        <img width="300" height="225" src="images/1510.jpg" alt="Durga Puja" class="item">
        <div class="item two"></div>
        <img width="300" height="225" src="images/1130.jpg" alt="Frog" class="item">
        <div class="item six"></div>
        <img class="item" width="300" height="202" src="images/0020.jpg" alt="Winning Moments">
        <div class="item three"></div>
        <img width="300" height="225" src="images/1490.jpg" alt="Diyas" class="item">
        <div class="item two"></div>
    </div>

    
<script>

$(document).ready(function(){
        $('.container').masonry({
          itemSelector: '.box',
          columnWidth: 300,
          gutterWidth: 20
        });
    });

  $(function(){
    
    var $container = $('#container');
    
    $('#container').masonry({
      columnWidth: 100
    });
    
    $container.masonry({
      itemSelector: '.box',
      columnWidth: 220,
      isAnimated: !Modernizr.csstransitions
    });
    
    // Sites using Masonry markup
    var $sites = $('#sites'),
        $loadingItem = $container.find('.loading');
        
    var ajaxError = function(){
      $loadingItem.text('Could not load examples :(');
    };
    
    // dynamically load sites using Masonry from Zootool
    $.getJSON('http://zootool.com/api/users/items/?username=desandro' +
        '&apikey=8b604e5d4841c2cd976241dd90d319d7' +
        '&tag=bestofmasonry&callback=?')
      .error( ajaxError )
      .success(function( data ){
        
        // proceed only if we have data
        if ( !data || !data.length ) {
          ajaxError();
          return;
        }
        var items = [],
            item, datum;
        
        for ( var i=0, len = data.length; i < len; i++ ) {
          datum = data[i];
          item = '<div class="item example"><a href="' + datum.url + '">'
            + '<img src="' + datum.image.replace('/l.', '/m.') + '" />'
            + '<b>' + datum.title + '</b>'
            + '</a></div>';
          items.push( item );
        }
        
        var $items = $( items.join('') );
        $items.imagesLoaded(function(){
          $container
            .masonry( 'remove', $loadingItem ).masonry()
            .append( $items ).masonry( 'appended', $items, true );
        });
        
      });
    
  });
</script>

app/views/tracks/new.html.erb
<h1>New track</h1>

<%= render 'form' %>

<%= link_to 'Back', tracks_path %>

app/views/tracks/search.html.erb
<p id="notice"><%= notice %></p>

         <table>
           <tr>
             <th>Title</th>
             <th>Genre</th>
             <th>Stream URL</th>
             <th>Cover url</th>
             <th></th>
             <th></th>
             <th></th>
           </tr>
          

         <% x = 0 %>
         <% while x < @tracks.length do %>
             <% @tracks.each do |track| %>
           <tr>
             <td><%= track[:title] %></td>
             <td><%= track[:genre] %></td>
             <td><%= track[:stream_url] %></td>
             <td><%= check_box_tag 'genre[]', track.id %></td>

             <% x += 1 %>
           </tr>
         <% end %>
         </table>
        <% end %>
         <br />
</div>

app/views/tracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @track.name %>
</p>

<p>
  <b>Track number:</b>
  <%= @track.track_number %>
</p>

<p>
  <b>Rating:</b>
  <%= @track.rating %>
</p>

<p>
  <b>Img url:</b>
  <%= @track.img_url %>
</p>

<p>
  <b>Duration:</b>
  <%= @track.duration %>
</p>

<p>
  <b>Location:</b>
  <%= @track.location %>
</p>

<p>
  <b>Album:</b>
  <%= @track.album_id %>
</p>

<p>
  <b>Genre:</b>
  <%= @track.genre_id %>
</p>

<p>
  <b>Artist:</b>
  <%= @track.artist_id %>
</p>


<%= link_to 'Edit', edit_track_path(@track) %> |
<%= link_to 'Back', tracks_path %>